"""empty message

Revision ID: 00322c8cd9a6
Revises: 
Create Date: 2018-04-26 12:03:55.958312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00322c8cd9a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agents_user_agent'), 'user_agents', ['user_agent'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('passhash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('invites', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', [sa.text('lower(username)')], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', [sa.text('lower(username)')], unique=False)
    op.create_index(op.f('ix_users_inviter_id'), 'users', ['inviter_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('hash', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyhashsalt', sa.String(length=128), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=39), server_default='0.0.0.0', nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=True),
    sa.Column('csrf_token', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['user_agent_id'], ['user_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_api_keys_active'), 'api_keys', ['active'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('time_sent', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('from_ip', sa.String(length=39), server_default='0.0.0.0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_invites_active'), 'invites', ['active'], unique=False)
    op.create_index(op.f('ix_invites_invitee_id'), 'invites', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_invites_inviter_id'), 'invites', ['inviter_id'], unique=False)
    op.create_table('permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission')
    )
    op.create_table('sessions',
    sa.Column('hash', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=39), server_default='0.0.0.0', nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=True),
    sa.Column('csrf_token', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['user_agent_id'], ['user_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_sessions_active'), 'sessions', ['active'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('api_permissions',
    sa.Column('api_key_hash', sa.String(length=10), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['api_key_hash'], ['api_keys.hash'], ),
    sa.PrimaryKeyConstraint('api_key_hash', 'permission')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_permissions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_active'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_invites_inviter_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_invitee_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_active'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_inviter_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_agents_user_agent'), table_name='user_agents')
    op.drop_table('user_agents')
    # ### end Alembic commands ###
