"""empty message

Revision ID: 3637fa2e0f53
Revises: 
Create Date: 2018-05-14 19:40:49.572621

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3637fa2e0f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['forums_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forums_category_id'), 'forums', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('passhash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('user_class_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('invites', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uploaded', sa.BigInteger(), server_default='5368709120', nullable=False),
    sa.Column('downloaded', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_class_id'], ['user_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_inviter_id'), 'users', ['inviter_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyhashsalt', sa.String(length=128), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), server_default='0.0.0.0', nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_revoked'), 'api_keys', ['revoked'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('forums_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('sticky', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], ),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forums_threads_poster_id'), 'forums_threads', ['poster_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('time_sent', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('from_ip', postgresql.INET(), server_default='0.0.0.0', nullable=False),
    sa.Column('expired', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_expired'), 'invites', ['expired'], unique=False)
    op.create_index(op.f('ix_invites_invitee_id'), 'invites', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_invites_inviter_id'), 'invites', ['inviter_id'], unique=False)
    op.create_table('secondary_class_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secondary_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secondary_class_id'], ['secondary_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persistent', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), server_default='0.0.0.0', nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('csrf_token', sa.String(length=24), nullable=False),
    sa.Column('expired', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expired'), 'sessions', ['expired'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('users_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission')
    )
    op.create_table('forums_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sticky', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forums_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forums_posts_poster_id'), 'forums_posts', ['poster_id'], unique=False)
    op.create_table('forums_posts_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forums_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forums_posts_edit_history')
    op.drop_index(op.f('ix_forums_posts_poster_id'), table_name='forums_posts')
    op.drop_table('forums_posts')
    op.drop_table('users_permissions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expired'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('secondary_class_assoc')
    op.drop_index(op.f('ix_invites_inviter_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_invitee_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_expired'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_forums_threads_poster_id'), table_name='forums_threads')
    op.drop_table('forums_threads')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_revoked'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_inviter_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forums_category_id'), table_name='forums')
    op.drop_table('forums')
    op.drop_table('user_classes')
    op.drop_table('secondary_classes')
    op.drop_table('forums_categories')
    # ### end Alembic commands ###
